#release configuration
#Wed May 24 15:10:58 PDT 2023
completedPhase=end-release
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.dev.org.springframework.samples\:spring-petclinic=3.0.2-SNAPSHOT
project.rel.org.springframework.samples\:spring-petclinic=3.0.1
project.scm.org.springframework.samples\:spring-petclinic.connection=scm\:git\:git\://github.com/jburns24/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.developerConnection=scm\:git\:git@github.com\:jburns24/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.tag=HEAD
project.scm.org.springframework.samples\:spring-petclinic.url=https\://github.com/jburns24/spring-petclinic
projectVersionPolicyId=default
pushChanges=true
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
scm.tag=spring-petclinic-3.0.1
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:jburns24/spring-petclinic.git
